export const TYPES = {
  //Products
  GET_ALL_PRODUCTS_LOADING: `GET_ALL_PRODUCTS_LOADING`,
  GET_ALL_PRODUCTS_SUCCESS: `GET_ALL_PRODUCTS_SUCCESS`,

  //order
  GET_ALL_Order_LOADING: `GET_ALL_Order_LOADING`,
  GET_ALL_Order_SUCCESS: `GET_ALL_Order_SUCCESS`,

  //Auth
  GET_AUTH_DATA: `GET_AUTH_DATA`,
  LOGOUT_USER: `LOGOUT_USER`,

  //User Cart
  UPDATE_USER_CART: `UPDATE_USER_CART`,
  EMPTY_CART: `EMPTY_CART`,

  // Socket Connection
  CONNECT_SOCKET: `CONNECT_SOCKET`,
  ///
  FILTER_PRODUCTS_LOADER: "FILTER_PRODUCTS_LOADER",
  FILTER_PRODUCTS_SUCCESS: "FILTER_PRODUCTS_SUCCESS",
  FILTER_PRODUCTS_FAIL: "FILTER_PRODUCTS_FAIL",
  QTY_INCREMENT: "QTY_INCREMENT",
};
